/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package seguridades;
import javax.swing.JOptionPane;
import utilidades.RelUtilidades;

/**
 *
 * @author prof_tes_a
 */
public class RelIniSes extends javax.swing.JFrame
{
    private RelUtilidades objUti;
    
    /**
     * Creates new form RelIniSes
     */
    public RelIniSes()
    {
        initComponents();
        objUti=new RelUtilidades();
        txtUsr.setText(getUsuario());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUsr = new javax.swing.JTextField();
        pwdCla = new javax.swing.JPasswordField();
        butAce = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de sesión");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Login01.png"))); // NOI18N

        jLabel2.setText("Usuario:");

        jLabel4.setText("Clave:");

        txtUsr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUsrFocusGained(evt);
            }
        });
        txtUsr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUsrKeyPressed(evt);
            }
        });

        pwdCla.setEchoChar('@');
        pwdCla.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwdClaFocusGained(evt);
            }
        });
        pwdCla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwdClaKeyPressed(evt);
            }
        });

        butAce.setMnemonic('A');
        butAce.setText("Aceptar");
        butAce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsr))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(butAce, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(pwdCla))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsr, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pwdCla, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butAce, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(400, 300));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsrFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUsrFocusGained
        txtUsr.selectAll();
    }//GEN-LAST:event_txtUsrFocusGained

    private void pwdClaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwdClaFocusGained
        pwdCla.selectAll();
    }//GEN-LAST:event_pwdClaFocusGained

    private void butAceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAceActionPerformed
        String strUsr, strCla;
        strUsr=txtUsr.getText();
        strCla=String.valueOf(pwdCla.getPassword());
        if (strUsr.length()>=3)
        {
            if (strCla.equals(strUsr))
            {
                JOptionPane.showMessageDialog(this, "Clave incorrecta.\nLa clave debe ser diferente al usuario.");
                pwdCla.selectAll();
                pwdCla.requestFocus();
            }
            else
            {
                RelPanPri objPanPri=new RelPanPri();
                objPanPri.setUsuarioBarraEstado(strUsr);
                objPanPri.setVisible(true);
                setUsuario();
                if (!guardarLog())
                    javax.swing.JOptionPane.showMessageDialog(this, "Problemas con el archivo de Log.");
                this.dispose();
            }
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Usuario incorrecto.\nEl usuario debe tener al menos 3 caracteres.");
            txtUsr.selectAll();
            txtUsr.requestFocus();
        }
    }//GEN-LAST:event_butAceActionPerformed

    private void txtUsrKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsrKeyPressed
        //Si se presiona la tecla ENTER pasar al siguiente control.
        if (evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER)
        {
            //pwdCla.requestFocus();
            txtUsr.transferFocus();
//             txtUsr.transferFocus();
        }
    }//GEN-LAST:event_txtUsrKeyPressed

    private void pwdClaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwdClaKeyPressed
        //Si se presiona la tecla ENTER ejecutar el bot{on "Aceptar".
        if (evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER)
        {
            butAceActionPerformed(null);
        }
    }//GEN-LAST:event_pwdClaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelIniSes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelIniSes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelIniSes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelIniSes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelIniSes().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAce;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField pwdCla;
    private javax.swing.JTextField txtUsr;
    // End of variables declaration//GEN-END:variables

    private boolean setUsuario()
    {
        boolean blnRes=true;
        try
        {
            //Leer el archivo de propiedades.
            java.util.Properties proArc=new java.util.Properties();
            java.io.FileInputStream fis=new java.io.FileInputStream(objUti.getDirectorioSistema() + "RelUsrSis.properties");
            proArc.load(fis);
            fis.close();
            //Actualizar el archivo de propiedades.
            java.io.FileOutputStream fos=new java.io.FileOutputStream(objUti.getDirectorioSistema() + "RelUsrSis.properties");
            proArc.put("Usuario", txtUsr.getText());
            proArc.store(fos, null);
            fos.close();
            proArc=null;
        }
        catch (java.io.FileNotFoundException e)
        {
            blnRes=false;
        }
        catch (java.io.IOException e)
        {
            blnRes=false;
        }
        catch (Exception e)
        {
            blnRes=false;
        }
        return blnRes;
    }
    
    private String getUsuario()
    {
        String strRes="";
        try
        {
            //Leer archivo de configuración "ZafUsrSis.properties".
            java.util.Properties proArc=new java.util.Properties();
            java.io.FileInputStream fis=new java.io.FileInputStream(objUti.getDirectorioSistema() + "RelUsrSis.properties");
            proArc.load(fis);
            fis.close();
            //Leer las propiedades.
            strRes=proArc.getProperty("Usuario");
            proArc=null;
        }
        catch (java.io.IOException e)
        {
            strRes="";
        }
        catch (Exception e)
        {
            strRes="";
        }
        return strRes;
    }

    private boolean guardarLog()
    {
        boolean blnRes=true;
        java.text.SimpleDateFormat objSimDatFor;
        objSimDatFor=new java.text.SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        try
        {
            java.io.FileWriter objFilWri=new java.io.FileWriter(objUti.getDirectorioSistema() + "RelTESLog.txt", true);
            java.io.BufferedWriter objBufWri=new java.io.BufferedWriter(objFilWri);
            java.io.PrintWriter objPriWri=new java.io.PrintWriter(objBufWri);
            objPriWri.print("Fecha de ingreso: " + objSimDatFor.format(new java.util.Date()));
            objPriWri.println();
            objPriWri.print("Usuario: " + txtUsr.getText());
            objPriWri.println();
            objPriWri.println();
            objPriWri.close();
        }
        catch(java.io.IOException e)
        {
            System.out.println("Excepción: " + e.toString());
            blnRes=false;
        }
        return blnRes;
    }
    
}
